// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: common.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Byz2PC_UpdateServerState_FullMethodName    = "/common.Byz2PC/UpdateServerState"
	Byz2PC_Callback_FullMethodName             = "/common.Byz2PC/Callback"
	Byz2PC_ProcessTxnSet_FullMethodName        = "/common.Byz2PC/ProcessTxnSet"
	Byz2PC_ProcessTxn_FullMethodName           = "/common.Byz2PC/ProcessTxn"
	Byz2PC_PrePrepare_FullMethodName           = "/common.Byz2PC/PrePrepare"
	Byz2PC_Prepare_FullMethodName              = "/common.Byz2PC/Prepare"
	Byz2PC_Commit_FullMethodName               = "/common.Byz2PC/Commit"
	Byz2PC_Sync_FullMethodName                 = "/common.Byz2PC/Sync"
	Byz2PC_TwoPCPrepareRequest_FullMethodName  = "/common.Byz2PC/TwoPCPrepareRequest"
	Byz2PC_TwoPCPrepareResponse_FullMethodName = "/common.Byz2PC/TwoPCPrepareResponse"
	Byz2PC_TwoPCCommitRequest_FullMethodName   = "/common.Byz2PC/TwoPCCommitRequest"
	Byz2PC_TwoPCCommit_FullMethodName          = "/common.Byz2PC/TwoPCCommit"
	Byz2PC_TwoPCAbort_FullMethodName           = "/common.Byz2PC/TwoPCAbort"
	Byz2PC_Performance_FullMethodName          = "/common.Byz2PC/Performance"
	Byz2PC_PrintBalance_FullMethodName         = "/common.Byz2PC/PrintBalance"
	Byz2PC_PrintDB_FullMethodName              = "/common.Byz2PC/PrintDB"
	Byz2PC_Benchmark_FullMethodName            = "/common.Byz2PC/Benchmark"
)

// Byz2PCClient is the client API for Byz2PC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Byz2PCClient interface {
	UpdateServerState(ctx context.Context, in *UpdateServerStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Callback(ctx context.Context, in *ProcessTxnResponse, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ProcessTxnSet(ctx context.Context, in *TxnSet, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ProcessTxn(ctx context.Context, in *TxnRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PrePrepare(ctx context.Context, in *PBFTRequestResponse, opts ...grpc.CallOption) (*PBFTRequestResponse, error)
	Prepare(ctx context.Context, in *PBFTRequestResponse, opts ...grpc.CallOption) (*PBFTRequestResponse, error)
	Commit(ctx context.Context, in *PBFTRequestResponse, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Sync(ctx context.Context, in *PBFTRequestResponse, opts ...grpc.CallOption) (*PBFTRequestResponse, error)
	TwoPCPrepareRequest(ctx context.Context, in *PBFTRequestResponse, opts ...grpc.CallOption) (*emptypb.Empty, error)
	TwoPCPrepareResponse(ctx context.Context, in *PBFTRequestResponse, opts ...grpc.CallOption) (*emptypb.Empty, error)
	TwoPCCommitRequest(ctx context.Context, in *PBFTRequestResponse, opts ...grpc.CallOption) (*PBFTRequestResponse, error)
	TwoPCCommit(ctx context.Context, in *TxnRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	TwoPCAbort(ctx context.Context, in *TxnRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Performance(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PerformanceResponse, error)
	PrintBalance(ctx context.Context, in *PrintBalanceRequest, opts ...grpc.CallOption) (*PrintBalanceResponse, error)
	PrintDB(ctx context.Context, in *PrintDBRequest, opts ...grpc.CallOption) (*PrintDBResponse, error)
	Benchmark(ctx context.Context, in *BenchmarkRequest, opts ...grpc.CallOption) (*PerformanceResponse, error)
}

type byz2PCClient struct {
	cc grpc.ClientConnInterface
}

func NewByz2PCClient(cc grpc.ClientConnInterface) Byz2PCClient {
	return &byz2PCClient{cc}
}

func (c *byz2PCClient) UpdateServerState(ctx context.Context, in *UpdateServerStateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Byz2PC_UpdateServerState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *byz2PCClient) Callback(ctx context.Context, in *ProcessTxnResponse, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Byz2PC_Callback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *byz2PCClient) ProcessTxnSet(ctx context.Context, in *TxnSet, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Byz2PC_ProcessTxnSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *byz2PCClient) ProcessTxn(ctx context.Context, in *TxnRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Byz2PC_ProcessTxn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *byz2PCClient) PrePrepare(ctx context.Context, in *PBFTRequestResponse, opts ...grpc.CallOption) (*PBFTRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PBFTRequestResponse)
	err := c.cc.Invoke(ctx, Byz2PC_PrePrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *byz2PCClient) Prepare(ctx context.Context, in *PBFTRequestResponse, opts ...grpc.CallOption) (*PBFTRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PBFTRequestResponse)
	err := c.cc.Invoke(ctx, Byz2PC_Prepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *byz2PCClient) Commit(ctx context.Context, in *PBFTRequestResponse, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Byz2PC_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *byz2PCClient) Sync(ctx context.Context, in *PBFTRequestResponse, opts ...grpc.CallOption) (*PBFTRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PBFTRequestResponse)
	err := c.cc.Invoke(ctx, Byz2PC_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *byz2PCClient) TwoPCPrepareRequest(ctx context.Context, in *PBFTRequestResponse, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Byz2PC_TwoPCPrepareRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *byz2PCClient) TwoPCPrepareResponse(ctx context.Context, in *PBFTRequestResponse, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Byz2PC_TwoPCPrepareResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *byz2PCClient) TwoPCCommitRequest(ctx context.Context, in *PBFTRequestResponse, opts ...grpc.CallOption) (*PBFTRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PBFTRequestResponse)
	err := c.cc.Invoke(ctx, Byz2PC_TwoPCCommitRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *byz2PCClient) TwoPCCommit(ctx context.Context, in *TxnRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Byz2PC_TwoPCCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *byz2PCClient) TwoPCAbort(ctx context.Context, in *TxnRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Byz2PC_TwoPCAbort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *byz2PCClient) Performance(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PerformanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerformanceResponse)
	err := c.cc.Invoke(ctx, Byz2PC_Performance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *byz2PCClient) PrintBalance(ctx context.Context, in *PrintBalanceRequest, opts ...grpc.CallOption) (*PrintBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintBalanceResponse)
	err := c.cc.Invoke(ctx, Byz2PC_PrintBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *byz2PCClient) PrintDB(ctx context.Context, in *PrintDBRequest, opts ...grpc.CallOption) (*PrintDBResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintDBResponse)
	err := c.cc.Invoke(ctx, Byz2PC_PrintDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *byz2PCClient) Benchmark(ctx context.Context, in *BenchmarkRequest, opts ...grpc.CallOption) (*PerformanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerformanceResponse)
	err := c.cc.Invoke(ctx, Byz2PC_Benchmark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Byz2PCServer is the server API for Byz2PC service.
// All implementations must embed UnimplementedByz2PCServer
// for forward compatibility.
type Byz2PCServer interface {
	UpdateServerState(context.Context, *UpdateServerStateRequest) (*emptypb.Empty, error)
	Callback(context.Context, *ProcessTxnResponse) (*emptypb.Empty, error)
	ProcessTxnSet(context.Context, *TxnSet) (*emptypb.Empty, error)
	ProcessTxn(context.Context, *TxnRequest) (*emptypb.Empty, error)
	PrePrepare(context.Context, *PBFTRequestResponse) (*PBFTRequestResponse, error)
	Prepare(context.Context, *PBFTRequestResponse) (*PBFTRequestResponse, error)
	Commit(context.Context, *PBFTRequestResponse) (*emptypb.Empty, error)
	Sync(context.Context, *PBFTRequestResponse) (*PBFTRequestResponse, error)
	TwoPCPrepareRequest(context.Context, *PBFTRequestResponse) (*emptypb.Empty, error)
	TwoPCPrepareResponse(context.Context, *PBFTRequestResponse) (*emptypb.Empty, error)
	TwoPCCommitRequest(context.Context, *PBFTRequestResponse) (*PBFTRequestResponse, error)
	TwoPCCommit(context.Context, *TxnRequest) (*emptypb.Empty, error)
	TwoPCAbort(context.Context, *TxnRequest) (*emptypb.Empty, error)
	Performance(context.Context, *emptypb.Empty) (*PerformanceResponse, error)
	PrintBalance(context.Context, *PrintBalanceRequest) (*PrintBalanceResponse, error)
	PrintDB(context.Context, *PrintDBRequest) (*PrintDBResponse, error)
	Benchmark(context.Context, *BenchmarkRequest) (*PerformanceResponse, error)
	mustEmbedUnimplementedByz2PCServer()
}

// UnimplementedByz2PCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedByz2PCServer struct{}

func (UnimplementedByz2PCServer) UpdateServerState(context.Context, *UpdateServerStateRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateServerState not implemented")
}
func (UnimplementedByz2PCServer) Callback(context.Context, *ProcessTxnResponse) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Callback not implemented")
}
func (UnimplementedByz2PCServer) ProcessTxnSet(context.Context, *TxnSet) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessTxnSet not implemented")
}
func (UnimplementedByz2PCServer) ProcessTxn(context.Context, *TxnRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessTxn not implemented")
}
func (UnimplementedByz2PCServer) PrePrepare(context.Context, *PBFTRequestResponse) (*PBFTRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrePrepare not implemented")
}
func (UnimplementedByz2PCServer) Prepare(context.Context, *PBFTRequestResponse) (*PBFTRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prepare not implemented")
}
func (UnimplementedByz2PCServer) Commit(context.Context, *PBFTRequestResponse) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedByz2PCServer) Sync(context.Context, *PBFTRequestResponse) (*PBFTRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedByz2PCServer) TwoPCPrepareRequest(context.Context, *PBFTRequestResponse) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TwoPCPrepareRequest not implemented")
}
func (UnimplementedByz2PCServer) TwoPCPrepareResponse(context.Context, *PBFTRequestResponse) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TwoPCPrepareResponse not implemented")
}
func (UnimplementedByz2PCServer) TwoPCCommitRequest(context.Context, *PBFTRequestResponse) (*PBFTRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TwoPCCommitRequest not implemented")
}
func (UnimplementedByz2PCServer) TwoPCCommit(context.Context, *TxnRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TwoPCCommit not implemented")
}
func (UnimplementedByz2PCServer) TwoPCAbort(context.Context, *TxnRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TwoPCAbort not implemented")
}
func (UnimplementedByz2PCServer) Performance(context.Context, *emptypb.Empty) (*PerformanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Performance not implemented")
}
func (UnimplementedByz2PCServer) PrintBalance(context.Context, *PrintBalanceRequest) (*PrintBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintBalance not implemented")
}
func (UnimplementedByz2PCServer) PrintDB(context.Context, *PrintDBRequest) (*PrintDBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintDB not implemented")
}
func (UnimplementedByz2PCServer) Benchmark(context.Context, *BenchmarkRequest) (*PerformanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Benchmark not implemented")
}
func (UnimplementedByz2PCServer) mustEmbedUnimplementedByz2PCServer() {}
func (UnimplementedByz2PCServer) testEmbeddedByValue()                {}

// UnsafeByz2PCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Byz2PCServer will
// result in compilation errors.
type UnsafeByz2PCServer interface {
	mustEmbedUnimplementedByz2PCServer()
}

func RegisterByz2PCServer(s grpc.ServiceRegistrar, srv Byz2PCServer) {
	// If the following call pancis, it indicates UnimplementedByz2PCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Byz2PC_ServiceDesc, srv)
}

func _Byz2PC_UpdateServerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Byz2PCServer).UpdateServerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byz2PC_UpdateServerState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Byz2PCServer).UpdateServerState(ctx, req.(*UpdateServerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Byz2PC_Callback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessTxnResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Byz2PCServer).Callback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byz2PC_Callback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Byz2PCServer).Callback(ctx, req.(*ProcessTxnResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Byz2PC_ProcessTxnSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxnSet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Byz2PCServer).ProcessTxnSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byz2PC_ProcessTxnSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Byz2PCServer).ProcessTxnSet(ctx, req.(*TxnSet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Byz2PC_ProcessTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Byz2PCServer).ProcessTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byz2PC_ProcessTxn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Byz2PCServer).ProcessTxn(ctx, req.(*TxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Byz2PC_PrePrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PBFTRequestResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Byz2PCServer).PrePrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byz2PC_PrePrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Byz2PCServer).PrePrepare(ctx, req.(*PBFTRequestResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Byz2PC_Prepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PBFTRequestResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Byz2PCServer).Prepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byz2PC_Prepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Byz2PCServer).Prepare(ctx, req.(*PBFTRequestResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Byz2PC_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PBFTRequestResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Byz2PCServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byz2PC_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Byz2PCServer).Commit(ctx, req.(*PBFTRequestResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Byz2PC_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PBFTRequestResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Byz2PCServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byz2PC_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Byz2PCServer).Sync(ctx, req.(*PBFTRequestResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Byz2PC_TwoPCPrepareRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PBFTRequestResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Byz2PCServer).TwoPCPrepareRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byz2PC_TwoPCPrepareRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Byz2PCServer).TwoPCPrepareRequest(ctx, req.(*PBFTRequestResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Byz2PC_TwoPCPrepareResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PBFTRequestResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Byz2PCServer).TwoPCPrepareResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byz2PC_TwoPCPrepareResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Byz2PCServer).TwoPCPrepareResponse(ctx, req.(*PBFTRequestResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Byz2PC_TwoPCCommitRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PBFTRequestResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Byz2PCServer).TwoPCCommitRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byz2PC_TwoPCCommitRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Byz2PCServer).TwoPCCommitRequest(ctx, req.(*PBFTRequestResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Byz2PC_TwoPCCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Byz2PCServer).TwoPCCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byz2PC_TwoPCCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Byz2PCServer).TwoPCCommit(ctx, req.(*TxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Byz2PC_TwoPCAbort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Byz2PCServer).TwoPCAbort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byz2PC_TwoPCAbort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Byz2PCServer).TwoPCAbort(ctx, req.(*TxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Byz2PC_Performance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Byz2PCServer).Performance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byz2PC_Performance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Byz2PCServer).Performance(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Byz2PC_PrintBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Byz2PCServer).PrintBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byz2PC_PrintBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Byz2PCServer).PrintBalance(ctx, req.(*PrintBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Byz2PC_PrintDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Byz2PCServer).PrintDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byz2PC_PrintDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Byz2PCServer).PrintDB(ctx, req.(*PrintDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Byz2PC_Benchmark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BenchmarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Byz2PCServer).Benchmark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Byz2PC_Benchmark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Byz2PCServer).Benchmark(ctx, req.(*BenchmarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Byz2PC_ServiceDesc is the grpc.ServiceDesc for Byz2PC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Byz2PC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "common.Byz2PC",
	HandlerType: (*Byz2PCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateServerState",
			Handler:    _Byz2PC_UpdateServerState_Handler,
		},
		{
			MethodName: "Callback",
			Handler:    _Byz2PC_Callback_Handler,
		},
		{
			MethodName: "ProcessTxnSet",
			Handler:    _Byz2PC_ProcessTxnSet_Handler,
		},
		{
			MethodName: "ProcessTxn",
			Handler:    _Byz2PC_ProcessTxn_Handler,
		},
		{
			MethodName: "PrePrepare",
			Handler:    _Byz2PC_PrePrepare_Handler,
		},
		{
			MethodName: "Prepare",
			Handler:    _Byz2PC_Prepare_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _Byz2PC_Commit_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _Byz2PC_Sync_Handler,
		},
		{
			MethodName: "TwoPCPrepareRequest",
			Handler:    _Byz2PC_TwoPCPrepareRequest_Handler,
		},
		{
			MethodName: "TwoPCPrepareResponse",
			Handler:    _Byz2PC_TwoPCPrepareResponse_Handler,
		},
		{
			MethodName: "TwoPCCommitRequest",
			Handler:    _Byz2PC_TwoPCCommitRequest_Handler,
		},
		{
			MethodName: "TwoPCCommit",
			Handler:    _Byz2PC_TwoPCCommit_Handler,
		},
		{
			MethodName: "TwoPCAbort",
			Handler:    _Byz2PC_TwoPCAbort_Handler,
		},
		{
			MethodName: "Performance",
			Handler:    _Byz2PC_Performance_Handler,
		},
		{
			MethodName: "PrintBalance",
			Handler:    _Byz2PC_PrintBalance_Handler,
		},
		{
			MethodName: "PrintDB",
			Handler:    _Byz2PC_PrintDB_Handler,
		},
		{
			MethodName: "Benchmark",
			Handler:    _Byz2PC_Benchmark_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common.proto",
}
